version: "3.9"
services:
    dev:
        build: .
        environment:
            CHOKIDAR_USEPOLLING: "true"
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules/
            - logvolume01:/var/log
volumes:
    logvolume01: {}
